
spring.application.name=Duinophile
server.port=8080

spring.mongodb.uri=mongodb+srv://sukirsukirthan21_db_user:DoSH3KJ6GZpAe6sT@cluster0.dqpiaca.mongodb.net/DuinophileDB?retryWrites=true&w=majority

spring.data.mongodb.auto-index-creation=true


logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO
logging.level.com.mongodb=DEBUG

