spring.application.name=Duinophile
spring.mongodb.uri=mongodb://localhost:27017/Duinophile
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.port=8080